### ISSUE TITLE
Unable to stream video

### ISSUE THREAD

**Issue by kalasaceo** [AbedElazizShe/LightCompressor#84] opened 2021-07-28 13:51 UTC
when i add android ffmpeg library the resultant video is unable to stream though the video can be played inside mobile device.
any idea  what should be change
https://github.com/SimformSolutionsPvtLtd/SSffmpegVideoOperation

**Comment by AbedElazizShe** [comment] 2021-08-11 00:40
@kalasaceo Thank you for opening the issue. Could you please try to use the latest version of the library with streamableFile path. Let me know if that solves your problem. There is a sample apk in the README for a quicker testing.

Thank you.

**Comment by AbedElazizShe** [comment] 2021-08-14 05:31
This is a duplicate of #22

**Closed by AbedElazizShe** 2021-08-14 05:31 UTC
