### ISSUE TITLE
Not able to share compressed video on WhatsApp.

### ISSUE THREAD

**Issue by Kedar1515** [AbedElazizShe/LightCompressor#80] opened 2021-06-29 12:04 UTC
After Compression I am sharing the video to the WhatsApp via Intent. Video is going forward to the WhatsApp but message is not sending by WhatsApp. Showing error like "Can't Send Video try another one."  I tried the same process with out Video Compression, that time Message got sent without any error. 
![bbad3283-0c27-4b67-a882-18a3dc0ccd3a](https://user-images.githubusercontent.com/25767698/123795628-d5cb5780-d901-11eb-86e0-64faa953c097.jpeg)
![7830e5d1-eecc-48aa-9dc2-2a538a949699](https://user-images.githubusercontent.com/25767698/123795646-da900b80-d901-11eb-9665-4fa7d711aeb1.jpeg)

**Comment by a-rizwan** [comment] 2021-07-07 07:03
same issue

**Comment by AbedElazizShe** [comment] 2021-09-01 15:07
I have been trying to fix this issue for weeks now. A few months ago, the library was working fine, i believe a new update by whatsapp caused this issue. Does anyone has details on what whatsapp accepts and what's not?

**Comment by emrisb** [comment] 2021-09-28 21:15
same issue for me too

**Comment by ashishHolofy** [comment] 2021-11-12 06:24
It is not just upload on whatsapp but also any upload in general

**Comment by AbedElazizShe** [comment] 2021-11-14 04:14
@ashishHolofy i have this problem with whatsapp upload for me, i can upload it anywhere including but not limited to telegram, gmail, drive, etc. It took me a very long time to find out the cause as it affects whatsapp only. It is mainly related to Audio. I am trying to fix that.

**Comment by AbedElazizShe** [comment] 2021-11-14 12:04
@Kedar1515 @ashishHolofy @a-rizwan After a very long investigation, and since the feature was working and stopped suddenly, Whatsapp- as you know- compresses media, and at a specific version, thier compression is affecting this library's MP4A audio. If you send the video as `document`, you will notice it is working perfectly fine. 

It is hard to tell what whatsapp is doing while compression. I will wait until further whatsapp update that improves their messy out-of-control compression for media.

I will close this issue for that reason. Please feel free to reopen if you're facing upload issue anywhere except whatsapp :D

**Closed by AbedElazizShe** 2021-11-14 12:04 UTC
Labels: help wanted, Investigating, InProgress
