### ISSUE TITLE
Playback of compressed video gets stuck on 0:01

### ISSUE THREAD

**Issue by chrissyast** [AbedElazizShe/LightCompressor#54] opened 2021-01-31 17:14 UTC
My code: https://github.com/chrissyast/StorageCleaner

Device: Pixel 4 API 27

Original video 720 x 1280, 2.6MB, 0:29
Output video 544 x 960 549kB, 0:29

Steps to reproduce:

1. Compress video
2. Open compressed video, press on screen during playback

Expected behaviour:
Playback continues

Actual behaviour:
Playback freezes, progress bar doesn't move

**Comment by AbedElazizShe** [comment] 2021-02-07 08:33
@chrissyast thank you for opening the issue and the provided details. 
It seems from the details you provided that the compression worked fine, so what playback ? Where are you trying to play the video?

**Comment by chrissyast** [comment] 2021-02-07 14:41
@AbedElazizShe thanks for your reply. I am playing the video from within the virtual device. I downloaded the video to my PC and it plays ok. Then I transferred to my physical device (OnePlus 6 API 29). Here the video continued to play when following the above steps, but on trying to move the progress bar, the video froze, and then had to pause and unpause the video, upon which the video would return to the start.

Original video https://f000.backblazeb2.com/file/RandomStuffCA/VID_20210131_155958.mp4
Compressed https://f000.backblazeb2.com/file/RandomStuffCA/VID_20210131_155958foo.mp4

**Comment by AbedElazizShe** [comment] 2021-02-18 13:12
I think your problem is not the compression but how you play the video. What do you use to play the video? Record a video of the scenario if you may. Thank you.

**Comment by chrissyast** [comment] 2021-02-21 19:18
@AbedElazizShe 

> What do you use to play the video?

It happens on the native player on my OnePlus 6 and also on VLC. On Chrome the embedded file from the link fails to load too. 

Screen recordings of playback
https://content.astles.dev/file/RandomStuffCA/21-02-21-14-22-51.mp4
https://content.astles.dev/file/RandomStuffCA/21-02-21-14-25-29.mp4

**Comment by AbedElazizShe** [comment] 2021-03-03 14:19
That's a problem related to the app you play the video in, try something else like vlc. The problem is not rtelated to the compressor. I will close this issue, feel free to re-open if the issue is related to compression.

**Closed by AbedElazizShe** 2021-03-03 14:19 UTC
Labels: Waiting for reply

**Comment by chrissyast** [comment] 2021-03-03 14:44
> try something else like vlc

The second recording in my previous comment is in vlc
