### ISSUE TITLE
Video cant compressor when newWith or newHeight is odd

### ISSUE THREAD

**Issue by kientrung0412** [AbedElazizShe/LightCompressor#59] opened 2021-03-01 07:01 UTC
Not all devices,  It happens on redmi note 8, miui 12

**Comment by kientrung0412** [comment] 2021-03-01 07:02
> Not all devices, It happens on redmi note 8, miui 12

**Comment by AbedElazizShe** [comment] 2021-03-03 15:00
@kientrung0412 thank you for the details, I will investigate that and will notify you when the fix is added.

**Comment by AbedElazizShe** [comment] 2021-03-21 08:05
I have added a check to ensure this does not happen, It will be released soon.

**Comment by AbedElazizShe** [comment] 2021-03-28 14:07
Issue fixed in version 0.8.1. Please let me know if you still have the issue. You can close the task if the problem is solved.

**Closed** 2021-04-11 06:02 UTC
Labels: Fixed
