### ISSUE TITLE
Can't work with Android Q

### ISSUE THREAD

**Issue by HemHemanth** [AbedElazizShe/LightCompressor#32] opened 2020-09-06 10:19 UTC
We can not get file path from Android Q, but this compressor work only if we pass source file path

**Comment by AbedElazizShe** [comment] 2020-09-06 12:54
Thank you for openning this issue. Could you please provide more details on the issue? My main device of testing is running Android Q. What kind of errors you're receiving ?

**Comment by HemHemanth** [comment] 2020-09-06 19:36
Receiving file path is deprecated in android from Android Q onwards we can not get video path from device. But your library asking to send source file path. Is there any alternative with your library to work with contentUri? 

Everywhere in my app i am using contentUri to display videos

**Comment by AbedElazizShe** [comment] 2020-09-07 11:47
Could you please look at the sample app, I created a function to save the file for a android Q a well, [here](https://github.com/AbedElazizShe/LightCompressor/blob/53c8529f38c6139b14ac275938a94025486a8627/app/src/main/java/com/abedelazizshe/lightcompressor/MainActivity.kt#L184) and here is the [file utils](https://github.com/AbedElazizShe/LightCompressor/blob/53c8529f38c6139b14ac275938a94025486a8627/app/src/main/java/com/abedelazizshe/lightcompressor/Utils.kt#L12)

**Comment by AbedElazizShe** [comment] 2020-09-13 14:20
Please reopen the issue if the solution provided above did not help. Will close it for now.

**Closed by AbedElazizShe** 2020-09-13 14:20 UTC

**Comment by mishra0007** [comment] 2020-10-09 19:12
I am getting the same issue right now.

I have provided 4 permission

**uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE
    uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE 
    uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION
    uses-permission android:name="android.permission.CAMERA**

and even given permission to my testing device.

D/path: /storage/emulated/0/download/Class 12 Maths - Continuity and Differentiation - Reuploaded (first video freezed on YouTube).mp4
W/System.err: java.io.FileNotFoundException: /storage/emulated/0/download/Class 12 Maths - Continuity and Differentiation - Reuploaded (first video freezed on YouTube).mp4: open failed: **EACCES (Permission denied)**
W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:496)
        at java.io.FileInputStream.<init>(FileInputStream.java:159)
        at com.example.video_compressor.MainActivity.saveVideoToInternalStorage(MainActivity.java:175)
        at com.example.video_compressor.MainActivity.onActivityResult(MainActivity.java:111)
        at android.app.Activity.dispatchActivityResult(Activity.java:8249)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4931)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4979)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7562)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
    Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
W/System.err:     at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7461)
        at libcore.io.IoBridge.open(IoBridge.java:482)
    	... 16 more
D/MediaPlayer: currentOpPackageName=com.example.video_compressor
**I/System.out: Source path: content://com.miui.gallery.open/raw/%2Fstorage%2Femulated%2F0%2Fdownload%2FClass%2012%20Maths%20-%20Continuity%20and%20Differentiation%20-%20Reuploaded%20(first%20video%20freezed%20on%20YouTube).mp4 can be invalid! or you don't have READ_EXTERNAL_STORAGE permission**
I/Toast: Show toast from OpPackageName:com.example.video_compressor, PackageName:com.example.video_compressor
D/MediaPlayerNative: getMetadata
V/MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
    cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
    cleanDrmObj: mDrmObj=null mDrmSessionId=null
W/System: A resource failed to call close. 
W/System: A resource failed to call close.
