### ISSUE TITLE
Green screen after compression

### ISSUE THREAD

**Issue by chendaxia65** [AbedElazizShe/LightCompressor#27] opened 2020-08-19 08:31 UTC
Huawei P9 compresses the video and sends it to iPhone 8. When it is played, it will be green. How can I solve this problem? Thank you

**Comment by AbedElazizShe** [comment] 2020-08-28 04:44
Thank you for opening this issue. I will investigate the issue during the weekend. 

Thank you

**Comment by AbedElazizShe** [comment] 2020-08-30 16:27
I tried many compressed videos on iPhone 8 and could not reproduce the issue. Could you please confirm that compressed videos in other phones have the same issue or just with Huawei?

**Comment by AbedElazizShe** [comment] 2020-09-06 12:55
Please re-open the issue if you're still having problems.

**Comment by ivanph** [comment] 2020-09-18 00:21
Hi @AbedElazizShe , great work with this library.

I'm experiencing this issue as well after converting a video on a Pixel 3 and trying to play it on MacOS using Quicktime, it is also reproducible in iOS and VLC.
I can provide details of the videos or anything else needed for debugging.
 Let me know if you prefer I open a new issue.
Thanks!!

**Comment by AbedElazizShe** [comment] 2020-09-18 01:21
Thank you ivanph for opening the issue and for the details. 

Could you please send me a screenshot of the compressed video file details showing bitrate, frame rate, and height and width. I find windows machine to give more details of a video .. so you can take a screen shot in a windows machine if you do have one.
Please let em know the parameters you passed for compression method.. and by any chance if you can pass me the original and the compressed video, I would be grateful.

Thank you

**Comment by ivanph** [comment] 2020-09-18 01:33
This is the output from ffmpeg
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'pixel.mp4':
  Metadata:
    major_brand     : iso6
    minor_version   : 1
    compatible_brands: mp42iso6avc1isom
    creation_time   : 2020-09-18T00:11:10.000000Z
  Duration: 00:05:00.05, start: 0.000000, bitrate: 782 kb/s
    Stream #0:0(eng): Video: h264 (Baseline) (avc1 / 0x31637661), yuv420p, 960x540, 654 kb/s, 24 fps, 24 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      creation_time   : 2020-09-18T00:09:38.000000Z
      handler_name    : VideoHandle
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 125 kb/s (default)
    Metadata:
      creation_time   : 2020-09-18T00:11:08.000000Z
      handler_name    : VideoHandle
At least one output file must be specified
```
You can get the original video here https://drive.google.com/file/d/1Izo9zWaSFA6h2XenxGOyUsGm00VmNMM7/view?usp=sharing
And the compressed file generated by the Pixel 3 https://drive.google.com/file/d/1-O3owYpaZJX-GBgB8SXfc9IXCHqObt2b/view?usp=sharing

Another detail is that playing the file on VLC only reproduces the audio _unless_ I disable hardware decoding on VLC settings.
This is all tested on MacOS and iOS, the file plays fine on the Pixel and also a Nexus 5x.

**Comment by AbedElazizShe** [comment] 2020-09-18 02:00
Thank you for the details.

From the numbers I think you're not using version 0.7.4? Could you please confirm that? 

I used the video and compressed it on pixel 2 xl. And could play it in ios and mac. Just let me know if you're having this issue in version 0.7.4.

Thank you

**Comment by ivanph** [comment] 2020-09-18 02:05
Yes, I'm on 0.7.3. I'll give it a try with the new version and get back to you.

**Comment by ivanph** [comment] 2020-09-18 02:27
Would you mind sharing the compressed video generated by your pixel 2 so I can try it on my end.

**Comment by AbedElazizShe** [comment] 2020-09-18 02:43
https://drive.google.com/file/d/1c0SbdbbE1I48su6g7toAPWjwvoo-h3wp/view?usp=sharing

**Comment by ivanph** [comment] 2020-09-18 05:21
I tried 0.7.4 but that didn't fix the issue.
Here's what I've found so far.
I ran `ffprobe -v error -show_format -show_streams file.mp4  > output.txt`
on my video and yours and the only difference that I found was this

From your video
```
...
color_range=tv
color_space=smpte170m
color_transfer=smpte170m
color_primaries=bt470bg
...
```

Mine

```
...
color_range=unknown
color_space=unknown
color_transfer=unknown
color_primaries=unknown
...
```

I then applied this 
`ffmpeg -i 0.7.4.mp4 -color_primaries bt470bg -color_trc smpte170m -colorspace smpte170m pixel_corrected.mp4` 
to my compressed video to set the values that were on yours.
After that the video plays just fine on both Mac and iOS.
I really have no idea what the reason for the color discrepancy could be and why this seems to be only an issue on Apple devices, my original compressed video plays just fine on Linux. 
Let me know if there's any other info I can provide for debugging but it seems that this might be a hardware specific issue since your Pixel 2 and my Pixel 3 use different GPUs.

**Comment by AbedElazizShe** [comment] 2020-09-18 05:39
Thank you ivanph, the details are great and now I know where the problem is, I will try to fix it later today and will inform you.

**Comment by ivanph** [comment] 2020-09-18 05:55
Awesome, thank you so much for all the help. 
I'm working on a react-native wrapper for this btw 😄 in case that's something you are interested in.

**Comment by AbedElazizShe** [comment] 2020-09-18 06:11
That's really awesome. Please inform me when you add the project to github, would love to help. I was focusing on Flutter and created a plugin for it.

**Comment by AbedElazizShe** [comment] 2020-09-19 04:19
Thank you very much for the great help. I am trying to figure out what values might cause this issue. I'd really appriciate if you can try this [apk](https://drive.google.com/file/d/10eiAWVNnj5EggM-Shf9puW7toozDDQjZ/view?usp=sharing). I don't have any devices with such an issue and emulators are not reliable in this kind of scenarios.  

In the previous apk, I tried [COLOR_RANGE_FULL](https://developer.android.com/reference/android/media/MediaFormat#COLOR_RANGE_FULL), and in this one, I am trying [COLOR_RANGE_LIMITED](https://developer.android.com/reference/android/media/MediaFormat#COLOR_RANGE_LIMITED) which described as `Limited range. Y component values range from 16 to 235 for 8-bit content. Cr, Cy values range from 16 to 240 for 8-bit content. This is the default for video content.`

**Comment by ivanph** [comment] 2020-09-19 23:01
Hey sorry I didn't get back to you sooner, I didn't have my laptop last night.
The issue is still there, I also tried a couple more values for the `MediaFormat.KEY_COLOR_FORMAT` key.
I have also been testing this project https://github.com/linkedin/LiTr and the videos play fine after compression.
I really appreciate all the work you've been putting into this issue, I've dealt with my share of device specific problems before and is not easy to debug.
Let me know if there is anything else I can do to help. Thanks.

**Comment by AbedElazizShe** [comment] 2020-09-20 03:07
Thank you very much Ivan, I appriciate you continues help. Yes I agree, device-specific issues are always tricky. Can I ask you for one more favor? I have added a Log to print media format data, with a tag `MEDIA FORMAT DATA`, Could you please try [this apk](https://drive.google.com/file/d/1sRn5qGKyHYWOUkQxfQOIjgow_937NZaO/view?usp=sharing) and send me the printed message? In my case, it looks like this;
 `E/MEDIA FORMAT DATA: {max-bitrate=4425162, csd-1=java.nio.HeapByteBuffer[pos=0 lim=8 cap=8], color-transfer=3, mime=video/avc, width=960, bitrate=4425162, color-range=2, frame-rate=30, color-standard=2, height=544, csd-0=java.nio.HeapByteBuffer[pos=0 lim=21 cap=21]}`

That data could be my best chance to undertsand the cause of the issue. 

Thank you :)

**Comment by ivanph** [comment] 2020-09-20 04:53
Here you go
```
2020-09-19 21:47:56.695 32620-32677/com.abedelazizshe.lightcompressor E/MEDIA FORMAT DATA: {
max-bitrate=436355, 
crop-right=959, 
level=1, 
mime=video/avc, 
profile=1, 
bitrate=436355, 
i-frame-period=48, 
priority=1, 
color-standard=0, 
csd-1=java.nio.HeapByteBuffer[pos=0 lim=8 cap=8], 
color-transfer=0, 
crop-bottom=543, 
prepend-sps-pps-to-idr-frames=1, 
crop-left=0, 
width=960, 
bitrate-mode=1, 
color-range=0, 
crop-top=0, 
frame-rate=24, 
height=544, 
csd-0=java.nio.HeapByteBuffer[pos=0 lim=17 cap=17]
}

```

**Comment by AbedElazizShe** [comment] 2020-09-22 16:30
Thank you. I tried so many way to fix the issue, including adding colors, changing profile and level, changing fps, changing video size, select colors dynamically, however, I am unable to fix the issue and Apple is not the greatest in providing documentation to their video playback requirements, every atricle provides different details.

Will keep researching and trying other ways. If by any chance anyone finds the potential cause, I'd appriciate the help.

**Comment by ivanph** [comment] 2020-09-22 18:28
Thanks again @AbedElazizShe
I also tried a few more settings to no avail. The only thing I know for sure, is that this only happens when decoding the video using hardware acceleration with [VideoToolbox](https://developer.apple.com/documentation/videotoolbox). That narrows the scope a little bit. I found another project that encodes videos just fine https://github.com/natario1/Transcoder. I'll try to compare their settings to yours and see if anything stands out.

**Comment by AbedElazizShe** [comment] 2020-10-01 14:57
I am thinking of re-writing the entire MP4Builder class and use the latest version of iosparser which may take a month or so, that might solve the problem with new encoders.

**Comment by AbedElazizShe** [comment] 2020-11-15 14:12
Fixed in version 0.7.7.

**Closed by AbedElazizShe** 2020-11-15 14:12 UTC
Labels: help wanted

**Comment by oleh-mryhlod** [comment] 2020-12-04 17:43
Hi @AbedElazizShe, Thanks for the lib.

Seems like I have exactly the same issue on Pixel 4 (Android 11), using 0.7.7.
There are the same `unknow` on some `color_` props on compressed video:
```
...
color_range=unknown
color_space=unknown
color_transfer=unknown
color_primaries=unknown
...
```
And using the same FFmpeg command resolves the issue with the video as on the [comment](https://github.com/AbedElazizShe/LightCompressor/issues/27#issuecomment-694657814).
Do you have any suggestions?

**Comment by AbedElazizShe** [comment] 2020-12-05 13:48
Thank you @oleh-mryhlod for the details. It seems only quicktime fails to play the compressed video from certain devices, especially pixels 3 -5. I marked the issue as resolved because I was using VLC on my Mac and iphones and everything was working just as expected. I have spent a very long time trying to solve the issue and it seems it is just not working with quicktime. I am considering re-writing the transcoder from scratch using the latest media codec apis but that's a huge task that won't be done in the near future.

**Comment by bipinvaylu** [comment] 2021-03-17 03:53
Hey @AbedElazizShe Thanks for this awesome library, But my app is built for iOS and Android both platforms so when Android user post video doesn't play on iOS app (by compressing video using this library). Do you have any update around rewriting?

**Comment by saggiyogesh** [comment] 2021-11-23 16:01
> Awesome, thank you so much for all the help. I'm working on a react-native wrapper for this btw 😄 in case that's something you are interested in.

Hi guys, 
Published react-native package for LightCompressor 

https://github.com/saggiyogesh/react-native-lightcompressor

**Comment by AbedElazizShe** [comment] 2022-01-21 13:51
> Hey @AbedElazizShe Thanks for this awesome library, But my app is built for iOS and Android both platforms so when Android user post video doesn't play on iOS app (by compressing video using this library). Do you have any update around rewriting?

Hi @bipinvaylu could you please try the latest version?

**Comment by bipinvaylu** [comment] 2022-01-23 04:13
Hi, Thanks for the update but now I am using the FFMPEG library for all kinds of video processing inside the app.
